name:                servant-client-generic
version:             0.1.0
github:              "collegevine/servant-client-generic"
license:             BSD3
author:              "Ralph Morton"
maintainer:          "ralphmorton@gmail.com"
copyright:           "2018 CollegeVine"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/collegevine/servant-client-generic#readme>

dependencies:
- base
- text
- mtl
- servant
- servant-server
- template-haskell
- http-types

default-extensions:
  AllowAmbiguousTypes
  ConstraintKinds
  DataKinds
  FlexibleContexts
  FlexibleInstances
  MultiParamTypeClasses
  OverloadedStrings
  PolyKinds
  ScopedTypeVariables
  TypeFamilies
  TypeOperators
  UndecidableInstances

ghc-options:         
  -Wall 
  -Werror 
  -Wincomplete-record-updates 
  -Wincomplete-uni-patterns 
  -Wredundant-constraints

library:
  source-dirs: src

